version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile-apache
    ports:
      - "80:80"
    volumes:
      - ./app:/var/www/html
      - ./server:/server
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: exampleuser
      DB_PASSWORD: examplepassword
      DB_DATABASE: exampledb
    depends_on:
      - db

  server:
    build:
      context: .
      dockerfile: Dockerfile-node
    ports:
      - "3000:3000"
    volumes:
      - server-volume:/server
    depends_on:
      - db

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: examplepassword
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepassword
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql  # Mount init.sql into MySQL container
      - db-data:/var/lib/mysql  # Persist data

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: examplepassword

volumes:
  server-volume:
  db-data:
