# Base image for Apache with PHP
FROM php:7.4-apache

# Install system dependencies
RUN apt-get update && \
    apt-get install -y \
        libpng-dev \
        libjpeg-dev \
        libfreetype6-dev \
        libzip-dev \
        zip \
        unzip \
        vim

# Configure PHP GD extension
RUN docker-php-ext-configure gd --with-freetype --with-jpeg

# Install PHP extensions
RUN docker-php-ext-install pdo_mysql gd zip

# Enable Apache modules
RUN a2enmod rewrite

# Install Composer
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

# Set working directory for Apache
WORKDIR /var/www/html

# Copy Apache virtual host configuration
COPY apache-config.conf /etc/apache2/sites-available/000-default.conf

# Copy the app files
COPY ./app/ /var/www/html

# Change ownership of Apache document root
RUN chown -R www-data:www-data /var/www/html

# Set working directory for the app
WORKDIR /var/www/html/app

# Install Composer dependencies
COPY ./app/composer.json ./app/composer.lock ./
RUN composer install --no-scripts --no-autoloader

# Copy the rest of the app files
COPY ./app .

# Generate Composer autoload files
RUN composer dump-autoload --optimize

# Expose port 80 for Apache
EXPOSE 80

# Command to run Apache
CMD ["apache2-foreground"]
