# Base image for Node.js
FROM node:14

# Set working directory for server
WORKDIR /server

# Copy package.json and package-lock.json to the working directory
COPY ./server/package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the server application code
COPY ./server/ .

# Expose port 3000 for the server
EXPOSE 3000

# Command to run the server
CMD ["npm", "start"]
